all:
  children:
    routers:
      children:
        vios_group:
          hosts:
            CE-A-R01:
              ansible_become: 'true'
              ansible_become_method: enable
              ansible_become_password: Cisco123
              ansible_connection: ansible.netcommon.network_cli
              ansible_host: 10.10.116.10
              ansible_network_os: cisco.ios.ios
              ansible_password: Cisco123
              ansible_user: admin
            CE-B-R01:
              ansible_become: 'true'
              ansible_become_method: enable
              ansible_become_password: Cisco123
              ansible_connection: ansible.netcommon.network_cli
              ansible_host: 10.10.200.6
              ansible_network_os: cisco.ios.ios
              ansible_password: Cisco123
              ansible_user: admin
